version: "2"

services:
  api:
    build: .
    working_dir: /go/src/github.com/eric-kansas/cross-pollinators-server
    volumes:
      - .:/go/src/github.com/eric-kansas/cross-pollinators-server
    ports:
      - '3030:3030'
    links:
      - db
    environment:
      # Standard Environment
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      PORT: '3030'

  db:
    image: postgres:latest
    ports:
        - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=pass1234
      - POSTGRES_USER=kansas
      - POSTGRES_DB=cross-pollinators-db
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
      