version: "2"

services:
  app:
    build: .
    image: golang:1.8
    working_dir: /go/src/github.com/eric-kansas/cross-pollinators-server
    volumes:
      - .:/go/src/github.com/eric-kansas/cross-pollinators-server
    ports:
      - '3030:3030'
    command: go run main.go
    environment:
      # Standard Environment
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      PORT: '3030'